//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Utilidades.Mensajes {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajesXynthesis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesXynthesis() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xynthesis.Utilidades.Mensajes.MensajesXynthesis", typeof(MensajesXynthesis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro ha sido actualizado con éxito..
        /// </summary>
        public static string Actualiza {
            get {
                return ResourceManager.GetString("Actualiza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizo el cambio de clave exitosamente.
        /// </summary>
        public static string CambClave {
            get {
                return ResourceManager.GetString("CambClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cobertura debe ser sola una (Movil, Nacional o Internacional).
        /// </summary>
        public static string CoberErra {
            get {
                return ResourceManager.GetString("CoberErra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clave fue cambiada correctamente.
        /// </summary>
        public static string ConfirmacionCambio {
            get {
                return ResourceManager.GetString("ConfirmacionCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo realizar el cambio de clave..
        /// </summary>
        public static string ConfirmacionCambioErrado {
            get {
                return ResourceManager.GetString("ConfirmacionCambioErrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo enviado correctamente..
        /// </summary>
        public static string ConfirmacionEnvio {
            get {
                return ResourceManager.GetString("ConfirmacionEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar correo..
        /// </summary>
        public static string ConfirmacionEnvioError {
            get {
                return ResourceManager.GetString("ConfirmacionEnvioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizo correctamente la retarificación.
        /// </summary>
        public static string CorrectaRetar {
            get {
                return ResourceManager.GetString("CorrectaRetar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo ingresado ya existe.
        /// </summary>
        public static string CorreoExistente {
            get {
                return ResourceManager.GetString("CorreoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo ingresado no esta registrado.
        /// </summary>
        public static string CorreoInvalido {
            get {
                return ResourceManager.GetString("CorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario o correo ingresado ya existen.
        /// </summary>
        public static string CorreoUsuario {
            get {
                return ResourceManager.GetString("CorreoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos son inválidos..
        /// </summary>
        public static string datosInvalido {
            get {
                return ResourceManager.GetString("datosInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro ha sido eliminado con éxito..
        /// </summary>
        public static string Elimina {
            get {
                return ResourceManager.GetString("Elimina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presento un error desconocido, por favor informar al administrador del sistema.
        /// </summary>
        public static string ErrDesconocido {
            get {
                return ResourceManager.GetString("ErrDesconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato de las fechas no es el correcto..
        /// </summary>
        public static string errFechas {
            get {
                return ResourceManager.GetString("errFechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe la información, No se permite crear el nuevo registro!.
        /// </summary>
        public static string existeRegi {
            get {
                return ResourceManager.GetString("existeRegi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible ejecutar el proceso de Retarificación.
        /// </summary>
        public static string falloRetari {
            get {
                return ResourceManager.GetString("falloRetari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo excedió el máximo de longitud..
        /// </summary>
        public static string Maxlon {
            get {
                return ResourceManager.GetString("Maxlon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clave no coincide..
        /// </summary>
        public static string NoPass {
            get {
                return ResourceManager.GetString("NoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No dispone de permisos para acceder.
        /// </summary>
        public static string NoPermisos {
            get {
                return ResourceManager.GetString("NoPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo procesar la solicitud, la información está relacionada o ya existe.
        /// </summary>
        public static string NoProcesa {
            get {
                return ResourceManager.GetString("NoProcesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clave o usuario no coincide o no existe..
        /// </summary>
        public static string NoSession {
            get {
                return ResourceManager.GetString("NoSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro ha sido creado con éxito..
        /// </summary>
        public static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo debe ser númerico..
        /// </summary>
        public static string numeroInv {
            get {
                return ResourceManager.GetString("numeroInv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proceso de Retarificación se realizó con éxito.
        /// </summary>
        public static string proRetar {
            get {
                return ResourceManager.GetString("proRetar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (*) El campo  es requerido.
        /// </summary>
        public static string Requerido {
            get {
                return ResourceManager.GetString("Requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo procesar la solicitud, no hay fechas para procesar.
        /// </summary>
        public static string sinfechas {
            get {
                return ResourceManager.GetString("sinfechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo procesar la solicitud, la fecha inicial debe ser mayor o igual a fecha final.
        /// </summary>
        public static string valFechas {
            get {
                return ResourceManager.GetString("valFechas", resourceCulture);
            }
        }
    }
}
