//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_budgettype
    {
        public xy_budgettype()
        {
            this.xy_companybudget = new HashSet<xy_companybudget>();
        }
    
        public int Ide_BudgetType { get; set; }
        public string Des_BudgetType { get; set; }
        public int Num_Period { get; set; }
    
        public virtual ICollection<xy_companybudget> xy_companybudget { get; set; }
    }
}
