//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_branch
    {
        public xy_branch()
        {
            this.xy_calls = new HashSet<xy_calls1>();
            this.xy_calls2 = new HashSet<xy_calls2>();
        }
    
        public int Ide_Branch { get; set; }
        public string Cod_Branch { get; set; }
        public string Nom_Branch { get; set; }
        public Nullable<float> Num_Latitude { get; set; }
        public Nullable<float> Num_Longitude { get; set; }
    
        public virtual ICollection<xy_calls1> xy_calls { get; set; }
        public virtual ICollection<xy_calls2> xy_calls2 { get; set; }
    }
}
