//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_calltypes
    {
        public sbyte Cod_CallTypeOXE { get; set; }
        public sbyte Ide_SourceType { get; set; }
        public sbyte Ide_CallType { get; set; }
    
        public virtual xy_calltype xy_calltype { get; set; }
        public virtual xy_sourcetype xy_sourcetype { get; set; }
    }
}
