//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_corporateplans
    {
        public int Ide_Plan { get; set; }
        public string Des_Plan { get; set; }
        public int Ide_Operator { get; set; }
        public System.DateTime Fec_DatePlan { get; set; }
        public sbyte Est_Enabled { get; set; }
    
        public virtual xy_operators1 xy_operators { get; set; }
    }
}
