//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_coverage1
    {
        public xy_coverage1()
        {
            this.xy_calls2 = new HashSet<xy_calls2>();
            this.xy_tickets = new HashSet<xy_tickets>();
            this.xy_indicativesxoperator = new HashSet<xy_indicativesxoperator>();
        }
    
        public int Ide_Coverage { get; set; }
        public sbyte Cod_Coverage { get; set; }
        public string Nom_Coverage { get; set; }
        public Nullable<bool> Movil { get; set; }
        public Nullable<bool> Nacional { get; set; }
        public Nullable<bool> Internacional { get; set; }
    
        public virtual ICollection<xy_calls2> xy_calls2 { get; set; }
        public virtual ICollection<xy_tickets> xy_tickets { get; set; }
        public virtual ICollection<xy_indicativesxoperator> xy_indicativesxoperator { get; set; }
    }
}
