//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_costxgeography
    {
        public int Ide_Operator { get; set; }
        public int Ide_Coverage { get; set; }
        public int Ide_GeographyTarget { get; set; }
        public System.DateTime Fec_InitDate { get; set; }
        public Nullable<System.DateTime> Fec_FinalDate { get; set; }
        public decimal Val_Cost { get; set; }
        public string Tip_Currency { get; set; }
        public decimal Num_Unit { get; set; }
        public string Tip_Rounding { get; set; }
        public decimal Por_Taxes { get; set; }
    }
}
