//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_communicationserver
    {
        public xy_communicationserver()
        {
            this.xy_calls = new HashSet<xy_calls>();
        }
    
        public int Ide_ServerType { get; set; }
        public string Nom_ServerType { get; set; }
    
        public virtual ICollection<xy_calls> xy_calls { get; set; }
    }
}
