//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_costcenters1
    {
        public xy_costcenters1()
        {
            this.xy_calls2 = new HashSet<xy_calls2>();
            this.xy_costcenterbudget = new HashSet<xy_costcenterbudget>();
            this.xy_subscriberxcostcenter = new HashSet<xy_subscriberxcostcenter>();
            this.xy_subscriber = new HashSet<xy_subscriber1>();
        }
    
        public int Ide_CostCenter { get; set; }
        public string Cod_CostCenter { get; set; }
        public string Nom_CostCenter { get; set; }
        public string Ide_ParentCostCenter { get; set; }
    
        public virtual ICollection<xy_calls2> xy_calls2 { get; set; }
        public virtual ICollection<xy_costcenterbudget> xy_costcenterbudget { get; set; }
        public virtual ICollection<xy_subscriberxcostcenter> xy_subscriberxcostcenter { get; set; }
        public virtual ICollection<xy_subscriber1> xy_subscriber { get; set; }
    }
}
