//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_configurationocs
    {
        public string Tip_Prefix { get; set; }
        public Nullable<int> Ide_Branch { get; set; }
        public string Num_Indicative { get; set; }
        public sbyte Num_Digits { get; set; }
        public sbyte Num_RemainingDigits { get; set; }
    }
}
