//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_configuracionrptprogramado1
    {
        public long ConfiguracionId { get; set; }
        public string Nombre { get; set; }
        public int FrecuenciaId { get; set; }
        public System.DateTime HoraEjecucion { get; set; }
        public string FormatoArchivo { get; set; }
        public string EmailFrom { get; set; }
        public string EmailCC { get; set; }
        public string Asunto { get; set; }
        public string Mensaje { get; set; }
        public string Filtro { get; set; }
        public string fechaInicial { get; set; }
        public string fechaFinal { get; set; }
        public string TipoFrecuencia { get; set; }
        public Nullable<int> programacion { get; set; }
        public Nullable<System.DateTime> ProxEjecucion { get; set; }
    }
}
