//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_currencyrates
    {
        public System.DateTime Fec_Date { get; set; }
        public float Val_Pesos { get; set; }
        public float Val_Dollars { get; set; }
        public float Val_Euros { get; set; }
    }
}
