//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_calls
    {
        public long Ide_SubscriberSource { get; set; }
        public long Ide_SubscriberTarget { get; set; }
        public string Ide_NumberSource { get; set; }
        public string Ide_NumberTarget { get; set; }
        public sbyte Ide_CallType { get; set; }
        public sbyte Ide_SourceType { get; set; }
        public int Ide_ServerType { get; set; }
        public int Ide_CostCenter { get; set; }
        public int Ide_GeographySource { get; set; }
        public int Ide_GeographyTarget { get; set; }
        public int Ide_Time { get; set; }
        public int Ide_Operator { get; set; }
        public sbyte Ide_Coverage { get; set; }
        public int Ide_Branch { get; set; }
        public long Ide_SubscriberEmployee { get; set; }
        public string Ide_NumberEmployee { get; set; }
        public int Ide_GeographyEmployee { get; set; }
        public System.DateTime Fec_Date { get; set; }
        public int Num_TimeSpanReal { get; set; }
        public int Num_TimeSpanCost { get; set; }
        public decimal Vlr_Cost_Pesos { get; set; }
        public decimal Vlr_Cost_Dollars { get; set; }
        public decimal Vlr_Cost_Euros { get; set; }
        public Nullable<decimal> Por_Taxes { get; set; }
        public Nullable<decimal> Vlr_Taxes_Pesos { get; set; }
        public Nullable<decimal> Vlr_Taxes_Dollars { get; set; }
        public Nullable<decimal> Vlr_Taxes_Euros { get; set; }
        public long Ide_Calls { get; set; }
        public Nullable<int> Ide_Trunk { get; set; }
        public Nullable<int> Num_CallEffectiveDuration { get; set; }
        public Nullable<int> Num_CallWaitingDuration { get; set; }
        public string Ide_SubscriberCalling { get; set; }
    
        public virtual xy_numbers xy_numbers { get; set; }
        public virtual xy_numbers xy_numbers1 { get; set; }
        public virtual xy_numbers xy_numbers2 { get; set; }
        public virtual xy_communicationserver xy_communicationserver { get; set; }
    }
}
