//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_coverage
    {
        public int Ide_Coverage { get; set; }
        public sbyte Cod_Coverage { get; set; }
        public string Nom_Coverage { get; set; }
        public Nullable<bool> Movil { get; set; }
        public Nullable<bool> Nacional { get; set; }
        public Nullable<bool> Internacional { get; set; }
    }
}
