//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_companybudget
    {
        public xy_companybudget()
        {
            this.xy_budgetbycommunication = new HashSet<xy_budgetbycommunication>();
            this.xy_costcenterbudget = new HashSet<xy_costcenterbudget>();
        }
    
        public int Ide_Budget { get; set; }
        public int Num_Year { get; set; }
        public System.DateTime Fec_DateBudget { get; set; }
        public System.DateTime Fec_BeginDate { get; set; }
        public System.DateTime Fec_EndDate { get; set; }
        public long Vlr_ValueBudget { get; set; }
        public string Des_Budget { get; set; }
        public int Ide_BudgetType { get; set; }
    
        public virtual ICollection<xy_budgetbycommunication> xy_budgetbycommunication { get; set; }
        public virtual xy_budgettype xy_budgettype { get; set; }
        public virtual ICollection<xy_costcenterbudget> xy_costcenterbudget { get; set; }
    }
}
