//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_geography
    {
        public int Ide_Geography { get; set; }
        public string Num_IndicativeCountry { get; set; }
        public string Nom_Country { get; set; }
        public string Num_IndicativeGrouping1 { get; set; }
        public string Nom_Grouping1 { get; set; }
        public string Num_IndicativeProvince { get; set; }
        public string Nom_Province { get; set; }
        public string Num_IndicativeCity { get; set; }
        public string Nom_City { get; set; }
        public int Tip_National { get; set; }
        public int Num_Digits { get; set; }
        public string Nom_Grouping2 { get; set; }
        public string Num_IndicativeGrouping2 { get; set; }
    }
}
