//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_methodbyrate
    {
        public int Ide_Method { get; set; }
        public int Ide_Rate { get; set; }
        public int Vlr_MinuteBegin { get; set; }
        public int Vlr_MinuteEnd { get; set; }
        public decimal Vlr_RateValue { get; set; }
    
        public virtual xy_rates1 xy_rates { get; set; }
    }
}
