//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_menus_
    {
        public int idMenus { get; set; }
        public string nombreMenu { get; set; }
        public string codMenu { get; set; }
        public string codMenuPadre { get; set; }
        public int Orden { get; set; }
        public string Acccion { get; set; }
        public string Controlador { get; set; }
    }
}
