//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_numbers1
    {
        public xy_numbers1()
        {
            this.xy_calls = new HashSet<xy_calls1>();
            this.xy_calls1 = new HashSet<xy_calls1>();
            this.xy_calls2 = new HashSet<xy_calls1>();
            this.xy_calls21 = new HashSet<xy_calls2>();
            this.xy_calls22 = new HashSet<xy_calls2>();
            this.xy_calls23 = new HashSet<xy_calls2>();
        }
    
        public string Ide_Number { get; set; }
        public Nullable<long> Tip_Extension { get; set; }
        public Nullable<int> Idcliente { get; set; }
    
        public virtual ICollection<xy_calls1> xy_calls { get; set; }
        public virtual ICollection<xy_calls1> xy_calls1 { get; set; }
        public virtual ICollection<xy_calls1> xy_calls2 { get; set; }
        public virtual ICollection<xy_calls2> xy_calls21 { get; set; }
        public virtual ICollection<xy_calls2> xy_calls22 { get; set; }
        public virtual ICollection<xy_calls2> xy_calls23 { get; set; }
    }
}
