//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_numbersxsubscriber
    {
        public string Ide_Number { get; set; }
        public System.DateTime Fec_Date { get; set; }
        public long Ide_Subscriber { get; set; }
        public string Tip_Subscriber { get; set; }
        public Nullable<int> Ide_ServerType { get; set; }
        public Nullable<int> Ide_Branch { get; set; }
        public Nullable<int> Ide_CostCenter { get; set; }
        public Nullable<int> Ide_Geography { get; set; }
        public string Num_AccessCode { get; set; }
        public Nullable<int> Ide_Plan { get; set; }
        public Nullable<int> Vlr_Plan { get; set; }
        public Nullable<int> Num_Minutes { get; set; }
    }
}
