//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_numbers
    {
        public xy_numbers()
        {
            this.xy_calls = new HashSet<xy_calls>();
            this.xy_calls1 = new HashSet<xy_calls>();
            this.xy_calls2 = new HashSet<xy_calls>();
        }
    
        public string Ide_Number { get; set; }
        public Nullable<long> Tip_Extension { get; set; }
        public Nullable<int> Idcliente { get; set; }
    
        public virtual ICollection<xy_calls> xy_calls { get; set; }
        public virtual ICollection<xy_calls> xy_calls1 { get; set; }
        public virtual ICollection<xy_calls> xy_calls2 { get; set; }
    }
}
