//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_numbers
    {
        public xy_numbers()
        {
            this.xy_calls = new HashSet<xy_calls>();
            this.xy_calls1 = new HashSet<xy_calls>();
            this.xy_calls2 = new HashSet<xy_calls>();
        }
    
        public string Ide_Number { get; set; }
        public Nullable<long> Tip_Extension { get; set; }
        public Nullable<int> Idcliente { get; set; }
    
        public virtual ICollection<xy_calls> xy_calls { get; set; }
        public virtual ICollection<xy_calls> xy_calls1 { get; set; }
        public virtual ICollection<xy_calls> xy_calls2 { get; set; }
    }
}
