//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_operador_tarifa_inter
    {
        public long idtarifaInter { get; set; }
        public long IdOperador { get; set; }
        public long IdPais { get; set; }
        public decimal VlrInternaMinsinIva { get; set; }
        public decimal VlrInternaMinconIva { get; set; }
        public Nullable<byte> Movil { get; set; }
        public Nullable<byte> Fijo { get; set; }
    }
}
