//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_operators1
    {
        public xy_operators1()
        {
            this.xy_calls2 = new HashSet<xy_calls2>();
            this.xy_corporateplans = new HashSet<xy_corporateplans>();
            this.xy_indicativesxoperator = new HashSet<xy_indicativesxoperator>();
        }
    
        public int Ide_Operator { get; set; }
        public string Cod_Operator { get; set; }
        public string Nom_Operator { get; set; }
        public Nullable<int> Ide_Coverage { get; set; }
        public Nullable<decimal> vlr_Cost { get; set; }
        public string Unit { get; set; }
        public Nullable<long> NumberDigits { get; set; }
    
        public virtual ICollection<xy_calls2> xy_calls2 { get; set; }
        public virtual ICollection<xy_corporateplans> xy_corporateplans { get; set; }
        public virtual ICollection<xy_indicativesxoperator> xy_indicativesxoperator { get; set; }
    }
}
