//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_operators
    {
        public int Ide_Operator { get; set; }
        public string Cod_Operator { get; set; }
        public string Nom_Operator { get; set; }
        public Nullable<int> Ide_Coverage { get; set; }
        public Nullable<decimal> vlr_Cost { get; set; }
        public string Unit { get; set; }
        public Nullable<long> NumberDigits { get; set; }
    }
}
