//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_operators
    {
        public int Ide_Operator { get; set; }
        public string Cod_Operator { get; set; }
        public string Nom_Operator { get; set; }
        public Nullable<int> Ide_Coverage { get; set; }
        public Nullable<decimal> vlr_Cost { get; set; }
        public string Unit { get; set; }
        public Nullable<long> NumberDigits { get; set; }
    }
}
