//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_roles_menus_
    {
        public long IdRolMen { get; set; }
        public long IdRol { get; set; }
        public long IdMenus { get; set; }
        public bool Activo { get; set; }
    }
}
