//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_reportes
    {
        public xy_reportes()
        {
            this.xy_configuracionreporte = new HashSet<xy_configuracionreporte>();
        }
    
        public int ReporteId { get; set; }
        public string Nombre { get; set; }
        public string NombreRpt { get; set; }
        public string MetodoRpt { get; set; }
    
        public virtual ICollection<xy_configuracionreporte> xy_configuracionreporte { get; set; }
    }
}
