//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_rates
    {
        public int Ide_Rate { get; set; }
        public string Des_Rate { get; set; }
        public Nullable<int> Ide_Zone { get; set; }
        public Nullable<int> Ide_Coverage { get; set; }
        public Nullable<int> Ide_Operator { get; set; }
        public int Num_Length { get; set; }
        public string Num_Prefix { get; set; }
        public Nullable<System.DateTime> Fec_InitDate { get; set; }
        public Nullable<System.DateTime> Fec_FinalDate { get; set; }
        public Nullable<decimal> Por_Taxes { get; set; }
        public Nullable<int> Cod_CostingMethod { get; set; }
    }
}
