//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_rol
    {
        public int Ide_Rol { get; set; }
        public string Nom_Rol { get; set; }
        public string Alias_Rol { get; set; }
        public string Des_Rol { get; set; }
    }
}
