//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_subscriber
    {
        public long Ide_Subscriber { get; set; }
        public string Nom_Subscriber { get; set; }
        public string Nom_DomainUser { get; set; }
        public string Tip_Subscriber { get; set; }
        public string Str_Password { get; set; }
        public string Cod_Subscriber { get; set; }
        public Nullable<long> Ide_CostCenter { get; set; }
        public Nullable<long> IdSucursal { get; set; }
        public Nullable<int> Id_Rol { get; set; }
        public string FechaCreacion { get; set; }
        public string Email { get; set; }
    }
}
