//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_subscriber
    {
        public long Ide_Subscriber { get; set; }
        public string Nom_Subscriber { get; set; }
        public string Nom_DomainUser { get; set; }
        public string Tip_Subscriber { get; set; }
        public string Str_Password { get; set; }
        public string Cod_Subscriber { get; set; }
        public Nullable<long> Ide_CostCenter { get; set; }
        public Nullable<long> IdSucursal { get; set; }
        public Nullable<int> Id_Rol { get; set; }
        public string FechaCreacion { get; set; }
        public string Email { get; set; }
    }
}
