//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_servers
    {
        public xy_servers()
        {
            this.xy_ticketinfo = new HashSet<xy_ticketinfo>();
        }
    
        public int Ide_Server { get; set; }
        public string ServerName { get; set; }
        public string Port { get; set; }
        public string Description { get; set; }
        public string TicketVersion { get; set; }
    
        public virtual ICollection<xy_ticketinfo> xy_ticketinfo { get; set; }
    }
}
