//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_subscriber1
    {
        public xy_subscriber1()
        {
            this.xy_calls2 = new HashSet<xy_calls2>();
            this.xy_calls21 = new HashSet<xy_calls2>();
            this.xy_calls22 = new HashSet<xy_calls2>();
            this.xy_subscriberxcostcenter = new HashSet<xy_subscriberxcostcenter>();
            this.xy_costcenters = new HashSet<xy_costcenters1>();
        }
    
        public long Ide_Subscriber { get; set; }
        public string Nom_Subscriber { get; set; }
        public string Nom_DomainUser { get; set; }
        public string Tip_Subscriber { get; set; }
        public string Str_Password { get; set; }
        public string Cod_Subscriber { get; set; }
        public Nullable<long> Ide_CostCenter { get; set; }
        public Nullable<long> IdSucursal { get; set; }
        public Nullable<int> Id_Rol { get; set; }
        public string FechaCreacion { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<xy_calls2> xy_calls2 { get; set; }
        public virtual ICollection<xy_calls2> xy_calls21 { get; set; }
        public virtual ICollection<xy_calls2> xy_calls22 { get; set; }
        public virtual ICollection<xy_subscriberxcostcenter> xy_subscriberxcostcenter { get; set; }
        public virtual ICollection<xy_costcenters1> xy_costcenters { get; set; }
    }
}
