//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_sourcetype
    {
        public xy_sourcetype()
        {
            this.xy_calls = new HashSet<xy_calls1>();
            this.xy_calls2 = new HashSet<xy_calls2>();
            this.xy_calltypes = new HashSet<xy_calltypes>();
        }
    
        public sbyte Ide_SourceType { get; set; }
        public string Nom_SourceType { get; set; }
    
        public virtual ICollection<xy_calls1> xy_calls { get; set; }
        public virtual ICollection<xy_calls2> xy_calls2 { get; set; }
        public virtual ICollection<xy_calltypes> xy_calltypes { get; set; }
    }
}
