//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_servertickets
    {
        public int Id_Server { get; set; }
        public string Nom_Server { get; set; }
        public string Nom_User { get; set; }
        public string Pwd_Password { get; set; }
        public string Tip_Formato { get; set; }
        public string Tip_Type { get; set; }
    }
}
