//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_telephoneseries
    {
        public int Ide_Serie { get; set; }
        public string Num_IndicativeCountry { get; set; }
        public string Num_IndicativeProvince { get; set; }
        public string Num_IndicativeCity { get; set; }
        public int Num_Serie { get; set; }
        public int Num_IndicativeSerie { get; set; }
    }
}
