//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_ticketinfo_copia
    {
        public int Ide_TicketInfo { get; set; }
        public string TicketVersion { get; set; }
        public string CalledNumber { get; set; }
        public string ChargedNumber { get; set; }
        public string ChargedUserName { get; set; }
        public string ChargedCostCenter { get; set; }
        public string ChargedCompany { get; set; }
        public string ChargedPartyNode { get; set; }
        public string Subaddress { get; set; }
        public string CallingNumber { get; set; }
        public string CallType { get; set; }
        public string CostType { get; set; }
        public string EndDateTime { get; set; }
        public string ChargeUnits { get; set; }
        public string CostInfo { get; set; }
        public string Duration { get; set; }
        public string TrunkIdentity { get; set; }
        public string TrunkGroupIdentity { get; set; }
        public string TrunkNode { get; set; }
        public string PersonalOrBusiness { get; set; }
        public string AccessCode { get; set; }
        public string SpecificChargeInfo { get; set; }
        public string BearerCapability { get; set; }
        public string HighLevelComp { get; set; }
        public string DataVolume { get; set; }
        public string UserToUserVolume { get; set; }
        public string ExternFacilities { get; set; }
        public string InternFacilities { get; set; }
        public string CallReference { get; set; }
        public string SegmentsRate1 { get; set; }
        public string SegmentsRate2 { get; set; }
        public string SegmentsRate3 { get; set; }
        public string ComType { get; set; }
        public string X25IncomingFlowRate { get; set; }
        public string X25OutgoingFlowRate { get; set; }
        public string Carrier { get; set; }
        public string InitialDialledNumber { get; set; }
        public string WaitingDuration { get; set; }
        public string EffectiveCallDuration { get; set; }
        public string RedirectedCallIndicator { get; set; }
        public string StartDateTime { get; set; }
        public string ActingExtensionNumber { get; set; }
        public string CalledNumberNode { get; set; }
        public string CallingNumberNode { get; set; }
        public string InitialDialledNumberNode { get; set; }
        public string ActingExtensionNumberNode { get; set; }
        public string TransitTrunkGroupIdentity { get; set; }
        public string NodeTimeOffset { get; set; }
        public Nullable<int> Ide_Server { get; set; }
    }
}
