//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_ticketsocs
    {
        public Nullable<int> UserSourceId { get; set; }
        public string UserSource { get; set; }
        public string NumberSource { get; set; }
        public Nullable<int> UserTargetId { get; set; }
        public string UserTarget { get; set; }
        public string NumberTarget { get; set; }
        public System.DateTime SessionIdTime { get; set; }
        public int Duration { get; set; }
        public Nullable<int> GatewayId { get; set; }
        public string Gateway { get; set; }
    }
}
