//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_time
    {
        public xy_time()
        {
            this.xy_calls2 = new HashSet<xy_calls2>();
        }
    
        public int Ide_Time { get; set; }
        public System.DateTime Fec_Date { get; set; }
        public sbyte Num_Hour { get; set; }
        public sbyte Num_Day { get; set; }
        public string Nom_Day { get; set; }
        public sbyte Num_Month { get; set; }
        public string Nom_Month { get; set; }
        public short Num_Year { get; set; }
        public sbyte Num_Semester { get; set; }
        public string Nom_Semester { get; set; }
        public sbyte Num_Quarter { get; set; }
        public string Nom_Quarter { get; set; }
        public sbyte Num_Week { get; set; }
        public string Nom_Week { get; set; }
        public bool Tip_Working { get; set; }
        public Nullable<int> Ide_ScheduleRange1 { get; set; }
        public string Nom_ScheduleRange1 { get; set; }
        public Nullable<int> Ide_ScheduleRange2 { get; set; }
        public string Nom_ScheduleRange2 { get; set; }
    
        public virtual ICollection<xy_calls2> xy_calls2 { get; set; }
    }
}
