//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_trunks
    {
        public xy_trunks()
        {
            this.xy_calls = new HashSet<xy_calls1>();
            this.xy_calls2 = new HashSet<xy_calls2>();
            this.xy_rates = new HashSet<xy_rates1>();
        }
    
        public int Ide_Trunk { get; set; }
        public string Nom_Trunk { get; set; }
    
        public virtual ICollection<xy_calls1> xy_calls { get; set; }
        public virtual ICollection<xy_calls2> xy_calls2 { get; set; }
        public virtual ICollection<xy_rates1> xy_rates { get; set; }
    }
}
