//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xy_tickets
    {
        public sbyte CallTypeId { get; set; }
        public string CallType { get; set; }
        public sbyte SourceTypeId { get; set; }
        public string SourceType { get; set; }
        public int ServerTypeId { get; set; }
        public string ServerType { get; set; }
        public string UserSource { get; set; }
        public string NumberSource { get; set; }
        public string UserTarget { get; set; }
        public string NumberTarget { get; set; }
        public System.DateTime DateTimeTicket { get; set; }
        public int Duration { get; set; }
        public string NumberEmployee { get; set; }
        public string TrunkIdentity { get; set; }
        public Nullable<int> Ide_Ticket { get; set; }
        public string EffectiveCallDuration { get; set; }
        public string WaitingDuration { get; set; }
        public string CallingNumber { get; set; }
        public int Coverage { get; set; }
    
        public virtual xy_coverage1 xy_coverage { get; set; }
    }
}
