//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class xydt_costcenters
    {
        public xydt_costcenters()
        {
            this.xydt_costcenters1 = new HashSet<xydt_costcenters>();
        }
    
        public int Ide_CostCenter { get; set; }
        public string Cod_CostCenter { get; set; }
        public string Nom_CostCenter { get; set; }
        public Nullable<int> Ide_ParentCostCenter { get; set; }
    
        public virtual ICollection<xydt_costcenters> xydt_costcenters1 { get; set; }
        public virtual xydt_costcenters xydt_costcenters2 { get; set; }
    }
}
