//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xynthesis.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class xynthesisEntities : DbContext
    {
        public xynthesisEntities()
            : base("name=xynthesisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<xy_subscriber> xy_subscriber { get; set; }
        public DbSet<xy_configuracionrptprogramado> xy_configuracionrptprogramado { get; set; }
        public DbSet<xy_coverage> xy_coverage { get; set; }
        public DbSet<xy_numbers> xy_numbers { get; set; }
        public DbSet<xy_numbersxsubscriber> xy_numbersxsubscriber { get; set; }
        public DbSet<xy_geography> xy_geography { get; set; }
        public DbSet<xy_pais> xy_pais { get; set; }
        public DbSet<xy_costcenters> xy_costcenters { get; set; }
        public DbSet<xy_cliente> xy_cliente { get; set; }
        public DbSet<xy_operators> xy_operators { get; set; }
        public DbSet<xy_operador_tarifa_inter> xy_operador_tarifa_inter { get; set; }
        public DbSet<xy_rates> xy_rates { get; set; }
        public DbSet<xy_sucursal> xy_sucursal { get; set; }
        public DbSet<xy_frecuencia> xy_frecuencia { get; set; }
        public DbSet<xy_reportes> xy_reportes { get; set; }
        public DbSet<xy_configuracionreporte> xy_configuracionreporte { get; set; }
        public DbSet<xy_rol> xy_rol { get; set; }
        public DbSet<xy_calls> xy_calls { get; set; }
        public DbSet<xy_areas> xy_areas { get; set; }
        public DbSet<xy_extencionessubcriber> xy_extencionessubcriber { get; set; }
    
        public virtual int xyp_DelCostCentre(Nullable<int> vParam)
        {
            var vParamParameter = vParam.HasValue ?
                new ObjectParameter("vParam", vParam) :
                new ObjectParameter("vParam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_DelCostCentre", vParamParameter);
        }
    
        public virtual int xyp_DelNumber(string ideNumber)
        {
            var ideNumberParameter = ideNumber != null ?
                new ObjectParameter("ideNumber", ideNumber) :
                new ObjectParameter("ideNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_DelNumber", ideNumberParameter);
        }
    
        public virtual int xyp_DelSucursal(Nullable<int> idSucursal)
        {
            var idSucursalParameter = idSucursal.HasValue ?
                new ObjectParameter("idSucursal", idSucursal) :
                new ObjectParameter("idSucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_DelSucursal", idSucursalParameter);
        }
    
        public virtual int xyp_InsCostCentre(string vCode, string vName, Nullable<int> iParent, ObjectParameter ireturnCode)
        {
            var vCodeParameter = vCode != null ?
                new ObjectParameter("vCode", vCode) :
                new ObjectParameter("vCode", typeof(string));
    
            var vNameParameter = vName != null ?
                new ObjectParameter("vName", vName) :
                new ObjectParameter("vName", typeof(string));
    
            var iParentParameter = iParent.HasValue ?
                new ObjectParameter("iParent", iParent) :
                new ObjectParameter("iParent", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_InsCostCentre", vCodeParameter, vNameParameter, iParentParameter, ireturnCode);
        }
    
        public virtual int xyp_InsNumber(string ideNumber, Nullable<bool> tipExtension)
        {
            var ideNumberParameter = ideNumber != null ?
                new ObjectParameter("ideNumber", ideNumber) :
                new ObjectParameter("ideNumber", typeof(string));
    
            var tipExtensionParameter = tipExtension.HasValue ?
                new ObjectParameter("tipExtension", tipExtension) :
                new ObjectParameter("tipExtension", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_InsNumber", ideNumberParameter, tipExtensionParameter);
        }
    
        public virtual int xyp_InsSucursal(string nombre_Sucursal, Nullable<int> ide_Geography)
        {
            var nombre_SucursalParameter = nombre_Sucursal != null ?
                new ObjectParameter("Nombre_Sucursal", nombre_Sucursal) :
                new ObjectParameter("Nombre_Sucursal", typeof(string));
    
            var ide_GeographyParameter = ide_Geography.HasValue ?
                new ObjectParameter("Ide_Geography", ide_Geography) :
                new ObjectParameter("Ide_Geography", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_InsSucursal", nombre_SucursalParameter, ide_GeographyParameter);
        }
    
        public virtual int xyp_UpdCostCentre(string vCode, string vName, Nullable<int> vParent, Nullable<int> vIdentity)
        {
            var vCodeParameter = vCode != null ?
                new ObjectParameter("vCode", vCode) :
                new ObjectParameter("vCode", typeof(string));
    
            var vNameParameter = vName != null ?
                new ObjectParameter("vName", vName) :
                new ObjectParameter("vName", typeof(string));
    
            var vParentParameter = vParent.HasValue ?
                new ObjectParameter("vParent", vParent) :
                new ObjectParameter("vParent", typeof(int));
    
            var vIdentityParameter = vIdentity.HasValue ?
                new ObjectParameter("vIdentity", vIdentity) :
                new ObjectParameter("vIdentity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_UpdCostCentre", vCodeParameter, vNameParameter, vParentParameter, vIdentityParameter);
        }
    
        public virtual int xyp_UpdNumberBySubscriber(string ideNumber, Nullable<System.DateTime> fecDate, Nullable<long> ideSubscriber, string tipSubscriber, Nullable<int> ideServerType, Nullable<int> ideBranch, Nullable<int> ideCostCenter, Nullable<int> ideGeography, string ideNumberOld)
        {
            var ideNumberParameter = ideNumber != null ?
                new ObjectParameter("ideNumber", ideNumber) :
                new ObjectParameter("ideNumber", typeof(string));
    
            var fecDateParameter = fecDate.HasValue ?
                new ObjectParameter("fecDate", fecDate) :
                new ObjectParameter("fecDate", typeof(System.DateTime));
    
            var ideSubscriberParameter = ideSubscriber.HasValue ?
                new ObjectParameter("ideSubscriber", ideSubscriber) :
                new ObjectParameter("ideSubscriber", typeof(long));
    
            var tipSubscriberParameter = tipSubscriber != null ?
                new ObjectParameter("tipSubscriber", tipSubscriber) :
                new ObjectParameter("tipSubscriber", typeof(string));
    
            var ideServerTypeParameter = ideServerType.HasValue ?
                new ObjectParameter("ideServerType", ideServerType) :
                new ObjectParameter("ideServerType", typeof(int));
    
            var ideBranchParameter = ideBranch.HasValue ?
                new ObjectParameter("ideBranch", ideBranch) :
                new ObjectParameter("ideBranch", typeof(int));
    
            var ideCostCenterParameter = ideCostCenter.HasValue ?
                new ObjectParameter("ideCostCenter", ideCostCenter) :
                new ObjectParameter("ideCostCenter", typeof(int));
    
            var ideGeographyParameter = ideGeography.HasValue ?
                new ObjectParameter("ideGeography", ideGeography) :
                new ObjectParameter("ideGeography", typeof(int));
    
            var ideNumberOldParameter = ideNumberOld != null ?
                new ObjectParameter("ideNumberOld", ideNumberOld) :
                new ObjectParameter("ideNumberOld", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_UpdNumberBySubscriber", ideNumberParameter, fecDateParameter, ideSubscriberParameter, tipSubscriberParameter, ideServerTypeParameter, ideBranchParameter, ideCostCenterParameter, ideGeographyParameter, ideNumberOldParameter);
        }
    
        public virtual int xyp_UpdSubscriber(Nullable<int> ideSubscriber, string nomSubscriber, string nomDomainUser, string tipSubscriber, string vPassword)
        {
            var ideSubscriberParameter = ideSubscriber.HasValue ?
                new ObjectParameter("ideSubscriber", ideSubscriber) :
                new ObjectParameter("ideSubscriber", typeof(int));
    
            var nomSubscriberParameter = nomSubscriber != null ?
                new ObjectParameter("nomSubscriber", nomSubscriber) :
                new ObjectParameter("nomSubscriber", typeof(string));
    
            var nomDomainUserParameter = nomDomainUser != null ?
                new ObjectParameter("nomDomainUser", nomDomainUser) :
                new ObjectParameter("nomDomainUser", typeof(string));
    
            var tipSubscriberParameter = tipSubscriber != null ?
                new ObjectParameter("tipSubscriber", tipSubscriber) :
                new ObjectParameter("tipSubscriber", typeof(string));
    
            var vPasswordParameter = vPassword != null ?
                new ObjectParameter("vPassword", vPassword) :
                new ObjectParameter("vPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_UpdSubscriber", ideSubscriberParameter, nomSubscriberParameter, nomDomainUserParameter, tipSubscriberParameter, vPasswordParameter);
        }
    
        public virtual ObjectResult<xyp_SelAllCostCentre_Result> xyp_SelAllCostCentre(Nullable<int> iStartIndex, Nullable<int> iEndIndex)
        {
            var iStartIndexParameter = iStartIndex.HasValue ?
                new ObjectParameter("iStartIndex", iStartIndex) :
                new ObjectParameter("iStartIndex", typeof(int));
    
            var iEndIndexParameter = iEndIndex.HasValue ?
                new ObjectParameter("iEndIndex", iEndIndex) :
                new ObjectParameter("iEndIndex", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelAllCostCentre_Result>("xyp_SelAllCostCentre", iStartIndexParameter, iEndIndexParameter);
        }
    
        public virtual ObjectResult<xyp_SelAllCostCentreParents_Result> xyp_SelAllCostCentreParents(string vParam, Nullable<int> iStartIndex, Nullable<int> iEndIndex)
        {
            var vParamParameter = vParam != null ?
                new ObjectParameter("vParam", vParam) :
                new ObjectParameter("vParam", typeof(string));
    
            var iStartIndexParameter = iStartIndex.HasValue ?
                new ObjectParameter("iStartIndex", iStartIndex) :
                new ObjectParameter("iStartIndex", typeof(int));
    
            var iEndIndexParameter = iEndIndex.HasValue ?
                new ObjectParameter("iEndIndex", iEndIndex) :
                new ObjectParameter("iEndIndex", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelAllCostCentreParents_Result>("xyp_SelAllCostCentreParents", vParamParameter, iStartIndexParameter, iEndIndexParameter);
        }
    
        public virtual ObjectResult<xyp_SelCountry_Result> xyp_SelCountry()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelCountry_Result>("xyp_SelCountry");
        }
    
        public virtual ObjectResult<xyp_SelCoverages_Result> xyp_SelCoverages()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelCoverages_Result>("xyp_SelCoverages");
        }
    
        public virtual ObjectResult<xyp_SelGeographyByCity_Result> xyp_SelGeographyByCity(string nomCountry, string nomProvince)
        {
            var nomCountryParameter = nomCountry != null ?
                new ObjectParameter("nomCountry", nomCountry) :
                new ObjectParameter("nomCountry", typeof(string));
    
            var nomProvinceParameter = nomProvince != null ?
                new ObjectParameter("nomProvince", nomProvince) :
                new ObjectParameter("nomProvince", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelGeographyByCity_Result>("xyp_SelGeographyByCity", nomCountryParameter, nomProvinceParameter);
        }
    
        public virtual ObjectResult<xyp_SelGeographyByCountry_Result> xyp_SelGeographyByCountry(string nomCountry)
        {
            var nomCountryParameter = nomCountry != null ?
                new ObjectParameter("nomCountry", nomCountry) :
                new ObjectParameter("nomCountry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelGeographyByCountry_Result>("xyp_SelGeographyByCountry", nomCountryParameter);
        }
    
        public virtual ObjectResult<xyp_SelNumbers_Result> xyp_SelNumbers(Nullable<int> iStartIndex, Nullable<int> iEndIndex)
        {
            var iStartIndexParameter = iStartIndex.HasValue ?
                new ObjectParameter("iStartIndex", iStartIndex) :
                new ObjectParameter("iStartIndex", typeof(int));
    
            var iEndIndexParameter = iEndIndex.HasValue ?
                new ObjectParameter("iEndIndex", iEndIndex) :
                new ObjectParameter("iEndIndex", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelNumbers_Result>("xyp_SelNumbers", iStartIndexParameter, iEndIndexParameter);
        }
    
        public virtual ObjectResult<xyp_SelOperators_Result> xyp_SelOperators(Nullable<int> ide_Operator_)
        {
            var ide_Operator_Parameter = ide_Operator_.HasValue ?
                new ObjectParameter("Ide_Operator_", ide_Operator_) :
                new ObjectParameter("Ide_Operator_", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelOperators_Result>("xyp_SelOperators", ide_Operator_Parameter);
        }
    
        public virtual ObjectResult<xyp_SelOperTarifInterna_Result> xyp_SelOperTarifInterna(Nullable<int> idtarifaInter1_)
        {
            var idtarifaInter1_Parameter = idtarifaInter1_.HasValue ?
                new ObjectParameter("idtarifaInter1_", idtarifaInter1_) :
                new ObjectParameter("idtarifaInter1_", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelOperTarifInterna_Result>("xyp_SelOperTarifInterna", idtarifaInter1_Parameter);
        }
    
        public virtual ObjectResult<xyp_SelServerType_Result> xyp_SelServerType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelServerType_Result>("xyp_SelServerType");
        }
    
        public virtual ObjectResult<xyp_SelSucursales_Result> xyp_SelSucursales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelSucursales_Result>("xyp_SelSucursales");
        }
    
        public virtual ObjectResult<xyp_SelUsuarioRol_Result> xyp_SelUsuarioRol(Nullable<long> ide_Subscriber_)
        {
            var ide_Subscriber_Parameter = ide_Subscriber_.HasValue ?
                new ObjectParameter("Ide_Subscriber_", ide_Subscriber_) :
                new ObjectParameter("Ide_Subscriber_", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelUsuarioRol_Result>("xyp_SelUsuarioRol", ide_Subscriber_Parameter);
        }
    
        public virtual int xyp_InsOperator(string codOperator_, string nomOperator_, Nullable<int> ideCoverage_, Nullable<decimal> vlr_Cost_, string unit_, Nullable<int> numberDigits_)
        {
            var codOperator_Parameter = codOperator_ != null ?
                new ObjectParameter("codOperator_", codOperator_) :
                new ObjectParameter("codOperator_", typeof(string));
    
            var nomOperator_Parameter = nomOperator_ != null ?
                new ObjectParameter("NomOperator_", nomOperator_) :
                new ObjectParameter("NomOperator_", typeof(string));
    
            var ideCoverage_Parameter = ideCoverage_.HasValue ?
                new ObjectParameter("IdeCoverage_", ideCoverage_) :
                new ObjectParameter("IdeCoverage_", typeof(int));
    
            var vlr_Cost_Parameter = vlr_Cost_.HasValue ?
                new ObjectParameter("vlr_Cost_", vlr_Cost_) :
                new ObjectParameter("vlr_Cost_", typeof(decimal));
    
            var unit_Parameter = unit_ != null ?
                new ObjectParameter("Unit_", unit_) :
                new ObjectParameter("Unit_", typeof(string));
    
            var numberDigits_Parameter = numberDigits_.HasValue ?
                new ObjectParameter("NumberDigits_", numberDigits_) :
                new ObjectParameter("NumberDigits_", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_InsOperator", codOperator_Parameter, nomOperator_Parameter, ideCoverage_Parameter, vlr_Cost_Parameter, unit_Parameter, numberDigits_Parameter);
        }
    
        public virtual int xyp_UpdOperator(Nullable<int> ide_Operator_, string codOperator_, string nomOperator_, Nullable<int> ideCoverage_, Nullable<decimal> vlr_Cost_, string unit_, Nullable<int> numberDigits_)
        {
            var ide_Operator_Parameter = ide_Operator_.HasValue ?
                new ObjectParameter("Ide_Operator_", ide_Operator_) :
                new ObjectParameter("Ide_Operator_", typeof(int));
    
            var codOperator_Parameter = codOperator_ != null ?
                new ObjectParameter("codOperator_", codOperator_) :
                new ObjectParameter("codOperator_", typeof(string));
    
            var nomOperator_Parameter = nomOperator_ != null ?
                new ObjectParameter("NomOperator_", nomOperator_) :
                new ObjectParameter("NomOperator_", typeof(string));
    
            var ideCoverage_Parameter = ideCoverage_.HasValue ?
                new ObjectParameter("IdeCoverage_", ideCoverage_) :
                new ObjectParameter("IdeCoverage_", typeof(int));
    
            var vlr_Cost_Parameter = vlr_Cost_.HasValue ?
                new ObjectParameter("vlr_Cost_", vlr_Cost_) :
                new ObjectParameter("vlr_Cost_", typeof(decimal));
    
            var unit_Parameter = unit_ != null ?
                new ObjectParameter("Unit_", unit_) :
                new ObjectParameter("Unit_", typeof(string));
    
            var numberDigits_Parameter = numberDigits_.HasValue ?
                new ObjectParameter("NumberDigits_", numberDigits_) :
                new ObjectParameter("NumberDigits_", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_UpdOperator", ide_Operator_Parameter, codOperator_Parameter, nomOperator_Parameter, ideCoverage_Parameter, vlr_Cost_Parameter, unit_Parameter, numberDigits_Parameter);
        }
    
        public virtual int xyp_RECalCostTicket(string fecIni, string fecFin)
        {
            var fecIniParameter = fecIni != null ?
                new ObjectParameter("fecIni", fecIni) :
                new ObjectParameter("fecIni", typeof(string));
    
            var fecFinParameter = fecFin != null ?
                new ObjectParameter("fecFin", fecFin) :
                new ObjectParameter("fecFin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_RECalCostTicket", fecIniParameter, fecFinParameter);
        }
    
        public virtual int xyp_UpdSucursal(Nullable<int> idSucursal_, string nombreSucursal_, Nullable<int> ide_Geography_)
        {
            var idSucursal_Parameter = idSucursal_.HasValue ?
                new ObjectParameter("IdSucursal_", idSucursal_) :
                new ObjectParameter("IdSucursal_", typeof(int));
    
            var nombreSucursal_Parameter = nombreSucursal_ != null ?
                new ObjectParameter("NombreSucursal_", nombreSucursal_) :
                new ObjectParameter("NombreSucursal_", typeof(string));
    
            var ide_Geography_Parameter = ide_Geography_.HasValue ?
                new ObjectParameter("Ide_Geography_", ide_Geography_) :
                new ObjectParameter("Ide_Geography_", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_UpdSucursal", idSucursal_Parameter, nombreSucursal_Parameter, ide_Geography_Parameter);
        }
    
        public virtual ObjectResult<xyp_SelActivityFirstAndLast_Result> xyp_SelActivityFirstAndLast(string startDateParameter, string endDateParameter, string usuario)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelActivityFirstAndLast_Result>("xyp_SelActivityFirstAndLast", startDateParameterParameter, endDateParameterParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<xyp_RepBudgetBySubscriber_Result> xyp_RepBudgetBySubscriber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_RepBudgetBySubscriber_Result>("xyp_RepBudgetBySubscriber");
        }
    
        public virtual ObjectResult<xyp_RepBudgetLimit_Result> xyp_RepBudgetLimit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_RepBudgetLimit_Result>("xyp_RepBudgetLimit");
        }
    
        public virtual ObjectResult<xyp_CallAmountByContraparte_Result> xyp_CallAmountByContraparte(string startDateParameter, string endDateParameter, string usuario)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_CallAmountByContraparte_Result>("xyp_CallAmountByContraparte", startDateParameterParameter, endDateParameterParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<xyp_SelCallAmountsBySubscriber_Result> xyp_SelCallAmountsBySubscriber(string startDateParameter, string endDateParameter, string usuario)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelCallAmountsBySubscriber_Result>("xyp_SelCallAmountsBySubscriber", startDateParameterParameter, endDateParameterParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<xyp_CallTypesAmountReport_Result> xyp_CallTypesAmountReport(string startDateParameter, string endDateParameter)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_CallTypesAmountReport_Result>("xyp_CallTypesAmountReport", startDateParameterParameter, endDateParameterParameter);
        }
    
        public virtual ObjectResult<xyp_NumberAmountsByOutSubscriber_Result> xyp_NumberAmountsByOutSubscriber(string startDateParameter, string endDateParameter, string usuario, string llamEntrad)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var llamEntradParameter = llamEntrad != null ?
                new ObjectParameter("LlamEntrad", llamEntrad) :
                new ObjectParameter("LlamEntrad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_NumberAmountsByOutSubscriber_Result>("xyp_NumberAmountsByOutSubscriber", startDateParameterParameter, endDateParameterParameter, usuarioParameter, llamEntradParameter);
        }
    
        public virtual ObjectResult<xyp_NumberAmountsBySubscriber_Result> xyp_NumberAmountsBySubscriber(string dStartDate, string dEndDate)
        {
            var dStartDateParameter = dStartDate != null ?
                new ObjectParameter("dStartDate", dStartDate) :
                new ObjectParameter("dStartDate", typeof(string));
    
            var dEndDateParameter = dEndDate != null ?
                new ObjectParameter("dEndDate", dEndDate) :
                new ObjectParameter("dEndDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_NumberAmountsBySubscriber_Result>("xyp_NumberAmountsBySubscriber", dStartDateParameter, dEndDateParameter);
        }
    
        public virtual ObjectResult<xyp_SelConsumeByCostCenter_Result> xyp_SelConsumeByCostCenter(string startDateParameter, string endDateParameter, string area, string cobertura)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(string));
    
            var coberturaParameter = cobertura != null ?
                new ObjectParameter("Cobertura", cobertura) :
                new ObjectParameter("Cobertura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelConsumeByCostCenter_Result>("xyp_SelConsumeByCostCenter", startDateParameterParameter, endDateParameterParameter, areaParameter, coberturaParameter);
        }
    
        public virtual ObjectResult<xyp_SelCostCentreByUser_Result> xyp_SelCostCentreByUser(Nullable<int> iIdSubscriber)
        {
            var iIdSubscriberParameter = iIdSubscriber.HasValue ?
                new ObjectParameter("iIdSubscriber", iIdSubscriber) :
                new ObjectParameter("iIdSubscriber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelCostCentreByUser_Result>("xyp_SelCostCentreByUser", iIdSubscriberParameter);
        }
    
        public virtual ObjectResult<xyp_SelConsumeByHistory_Result> xyp_SelConsumeByHistory(string startDateParameter, string endDateParameter, string area, string anio, string mes)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(string));
    
            var anioParameter = anio != null ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(string));
    
            var mesParameter = mes != null ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelConsumeByHistory_Result>("xyp_SelConsumeByHistory", startDateParameterParameter, endDateParameterParameter, areaParameter, anioParameter, mesParameter);
        }
    
        public virtual ObjectResult<xyp_SelDetailChampCallCost_Result> xyp_SelDetailChampCallCost(string startDateParameter, string endDateParameter, string area, string llamEntrad, string origen)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(string));
    
            var llamEntradParameter = llamEntrad != null ?
                new ObjectParameter("LlamEntrad", llamEntrad) :
                new ObjectParameter("LlamEntrad", typeof(string));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelDetailChampCallCost_Result>("xyp_SelDetailChampCallCost", startDateParameterParameter, endDateParameterParameter, areaParameter, llamEntradParameter, origenParameter);
        }
    
        public virtual ObjectResult<xyp_SelFrequentExtensionNumber_Result> xyp_SelFrequentExtensionNumber(string startDateParameter, string endDateParameter)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelFrequentExtensionNumber_Result>("xyp_SelFrequentExtensionNumber", startDateParameterParameter, endDateParameterParameter);
        }
    
        public virtual ObjectResult<xyp_ReceiveCalls_Result> xyp_ReceiveCalls(string startDateParameter, string endDateParameter, string usuario, string area)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_ReceiveCalls_Result>("xyp_ReceiveCalls", startDateParameterParameter, endDateParameterParameter, usuarioParameter, areaParameter);
        }
    
        public virtual ObjectResult<xyp_RepReceiveCallsLlamEntranSalien_Result> xyp_RepReceiveCallsLlamEntranSalien(string startDateParameter, string endDateParameter, string usuario, string area)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_RepReceiveCallsLlamEntranSalien_Result>("xyp_RepReceiveCallsLlamEntranSalien", startDateParameterParameter, endDateParameterParameter, usuarioParameter, areaParameter);
        }
    
        public virtual ObjectResult<xyp_ReceiveAndTransferCalls_Result> xyp_ReceiveAndTransferCalls(string startDateParameter, string endDateParameter, string usuario)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_ReceiveAndTransferCalls_Result>("xyp_ReceiveAndTransferCalls", startDateParameterParameter, endDateParameterParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<xyp_ReceiveCallsTiempoPromedio_Result> xyp_ReceiveCallsTiempoPromedio(string startDateParameter, string endDateParameter, string usuario, string area)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_ReceiveCallsTiempoPromedio_Result>("xyp_ReceiveCallsTiempoPromedio", startDateParameterParameter, endDateParameterParameter, usuarioParameter, areaParameter);
        }
    
        public virtual ObjectResult<xyp_RepConsolidadoCoberturaLLamadas_Result> xyp_RepConsolidadoCoberturaLLamadas(string startDateParameter, string endDateParameter, string usuario, string area)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_RepConsolidadoCoberturaLLamadas_Result>("xyp_RepConsolidadoCoberturaLLamadas", startDateParameterParameter, endDateParameterParameter, usuarioParameter, areaParameter);
        }
    
        public virtual ObjectResult<xyp_ReceiveCallsTiempoPromedio_repo_Result> xyp_ReceiveCallsTiempoPromedio_repo(string startDateParameter, string endDateParameter)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_ReceiveCallsTiempoPromedio_repo_Result>("xyp_ReceiveCallsTiempoPromedio_repo", startDateParameterParameter, endDateParameterParameter);
        }
    
        public virtual ObjectResult<xyp_RepPromedioLlamadasHora_Result> xyp_RepPromedioLlamadasHora(string dStartDate, string dEndDate, string usuario, string area, string rango)
        {
            var dStartDateParameter = dStartDate != null ?
                new ObjectParameter("dStartDate", dStartDate) :
                new ObjectParameter("dStartDate", typeof(string));
    
            var dEndDateParameter = dEndDate != null ?
                new ObjectParameter("dEndDate", dEndDate) :
                new ObjectParameter("dEndDate", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(string));
    
            var rangoParameter = rango != null ?
                new ObjectParameter("Rango", rango) :
                new ObjectParameter("Rango", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_RepPromedioLlamadasHora_Result>("xyp_RepPromedioLlamadasHora", dStartDateParameter, dEndDateParameter, usuarioParameter, areaParameter, rangoParameter);
        }
    
        public virtual ObjectResult<xyp_RepGrafNumberAmountsBySubscriber_Result> xyp_RepGrafNumberAmountsBySubscriber(string startDateParameter, string endDateParameter, string usuario, string area)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_RepGrafNumberAmountsBySubscriber_Result>("xyp_RepGrafNumberAmountsBySubscriber", startDateParameterParameter, endDateParameterParameter, usuarioParameter, areaParameter);
        }
    
        public virtual int xyp_Updoperador_tarifa_inter(Nullable<int> idtarifaInter_, Nullable<int> idOperador_, Nullable<int> idPais_, Nullable<decimal> vlrInternaMinsinIva_, Nullable<decimal> vlrInternaMinconIva_, Nullable<sbyte> movil_, Nullable<sbyte> fijo_)
        {
            var idtarifaInter_Parameter = idtarifaInter_.HasValue ?
                new ObjectParameter("idtarifaInter_", idtarifaInter_) :
                new ObjectParameter("idtarifaInter_", typeof(int));
    
            var idOperador_Parameter = idOperador_.HasValue ?
                new ObjectParameter("IdOperador_", idOperador_) :
                new ObjectParameter("IdOperador_", typeof(int));
    
            var idPais_Parameter = idPais_.HasValue ?
                new ObjectParameter("IdPais_", idPais_) :
                new ObjectParameter("IdPais_", typeof(int));
    
            var vlrInternaMinsinIva_Parameter = vlrInternaMinsinIva_.HasValue ?
                new ObjectParameter("VlrInternaMinsinIva_", vlrInternaMinsinIva_) :
                new ObjectParameter("VlrInternaMinsinIva_", typeof(decimal));
    
            var vlrInternaMinconIva_Parameter = vlrInternaMinconIva_.HasValue ?
                new ObjectParameter("VlrInternaMinconIva_", vlrInternaMinconIva_) :
                new ObjectParameter("VlrInternaMinconIva_", typeof(decimal));
    
            var movil_Parameter = movil_.HasValue ?
                new ObjectParameter("Movil_", movil_) :
                new ObjectParameter("Movil_", typeof(sbyte));
    
            var fijo_Parameter = fijo_.HasValue ?
                new ObjectParameter("Fijo_", fijo_) :
                new ObjectParameter("Fijo_", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_Updoperador_tarifa_inter", idtarifaInter_Parameter, idOperador_Parameter, idPais_Parameter, vlrInternaMinsinIva_Parameter, vlrInternaMinconIva_Parameter, movil_Parameter, fijo_Parameter);
        }
    
        public virtual int xyp_Insoperador_tarifa_inter(Nullable<int> idOperador_, Nullable<int> idPais_, Nullable<decimal> vlrInternaMinsinIva_, Nullable<decimal> vlrInternaMinconIva_, Nullable<sbyte> movil_, Nullable<sbyte> fijo_)
        {
            var idOperador_Parameter = idOperador_.HasValue ?
                new ObjectParameter("IdOperador_", idOperador_) :
                new ObjectParameter("IdOperador_", typeof(int));
    
            var idPais_Parameter = idPais_.HasValue ?
                new ObjectParameter("IdPais_", idPais_) :
                new ObjectParameter("IdPais_", typeof(int));
    
            var vlrInternaMinsinIva_Parameter = vlrInternaMinsinIva_.HasValue ?
                new ObjectParameter("VlrInternaMinsinIva_", vlrInternaMinsinIva_) :
                new ObjectParameter("VlrInternaMinsinIva_", typeof(decimal));
    
            var vlrInternaMinconIva_Parameter = vlrInternaMinconIva_.HasValue ?
                new ObjectParameter("VlrInternaMinconIva_", vlrInternaMinconIva_) :
                new ObjectParameter("VlrInternaMinconIva_", typeof(decimal));
    
            var movil_Parameter = movil_.HasValue ?
                new ObjectParameter("Movil_", movil_) :
                new ObjectParameter("Movil_", typeof(sbyte));
    
            var fijo_Parameter = fijo_.HasValue ?
                new ObjectParameter("Fijo_", fijo_) :
                new ObjectParameter("Fijo_", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_Insoperador_tarifa_inter", idOperador_Parameter, idPais_Parameter, vlrInternaMinsinIva_Parameter, vlrInternaMinconIva_Parameter, movil_Parameter, fijo_Parameter);
        }
    
        public virtual ObjectResult<xyp_RepTarificacionEntraSalieTrans_Result> xyp_RepTarificacionEntraSalieTrans(string dStartDate, string dEndDate, string usuario, string area, string sucursal)
        {
            var dStartDateParameter = dStartDate != null ?
                new ObjectParameter("dStartDate", dStartDate) :
                new ObjectParameter("dStartDate", typeof(string));
    
            var dEndDateParameter = dEndDate != null ?
                new ObjectParameter("dEndDate", dEndDate) :
                new ObjectParameter("dEndDate", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(string));
    
            var sucursalParameter = sucursal != null ?
                new ObjectParameter("Sucursal", sucursal) :
                new ObjectParameter("Sucursal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_RepTarificacionEntraSalieTrans_Result>("xyp_RepTarificacionEntraSalieTrans", dStartDateParameter, dEndDateParameter, usuarioParameter, areaParameter, sucursalParameter);
        }
    
        public virtual ObjectResult<xyp_SelReports_Result> xyp_SelReports(Nullable<int> idRepProgramado)
        {
            var idRepProgramadoParameter = idRepProgramado.HasValue ?
                new ObjectParameter("IdRepProgramado", idRepProgramado) :
                new ObjectParameter("IdRepProgramado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelReports_Result>("xyp_SelReports", idRepProgramadoParameter);
        }
    
        public virtual int xyp_DelRepProgra(Nullable<int> confId)
        {
            var confIdParameter = confId.HasValue ?
                new ObjectParameter("ConfId", confId) :
                new ObjectParameter("ConfId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_DelRepProgra", confIdParameter);
        }
    
        public virtual ObjectResult<xyp_RepCallOpenAndClosed_Result> xyp_RepCallOpenAndClosed(string startDateParameter, string endDateParameter, string callDurationParameter, string usuario, string llamEntrad)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var callDurationParameterParameter = callDurationParameter != null ?
                new ObjectParameter("CallDurationParameter", callDurationParameter) :
                new ObjectParameter("CallDurationParameter", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var llamEntradParameter = llamEntrad != null ?
                new ObjectParameter("LlamEntrad", llamEntrad) :
                new ObjectParameter("LlamEntrad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_RepCallOpenAndClosed_Result>("xyp_RepCallOpenAndClosed", startDateParameterParameter, endDateParameterParameter, callDurationParameterParameter, usuarioParameter, llamEntradParameter);
        }
    
        public virtual int xyp_UpdRepProgra(Nullable<int> confId, string repId)
        {
            var confIdParameter = confId.HasValue ?
                new ObjectParameter("ConfId", confId) :
                new ObjectParameter("ConfId", typeof(int));
    
            var repIdParameter = repId != null ?
                new ObjectParameter("RepId", repId) :
                new ObjectParameter("RepId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_UpdRepProgra", confIdParameter, repIdParameter);
        }
    
        public virtual ObjectResult<xyp_SelOperxCoberMovil_Result> xyp_SelOperxCoberMovil()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelOperxCoberMovil_Result>("xyp_SelOperxCoberMovil");
        }
    
        public virtual ObjectResult<xyp_NumberAmountsByInSubscriber_Result> xyp_NumberAmountsByInSubscriber(string startDateParameter, string endDateParameter, string usuario, string llamEntrad, string extens)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var llamEntradParameter = llamEntrad != null ?
                new ObjectParameter("LlamEntrad", llamEntrad) :
                new ObjectParameter("LlamEntrad", typeof(string));
    
            var extensParameter = extens != null ?
                new ObjectParameter("Extens", extens) :
                new ObjectParameter("Extens", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_NumberAmountsByInSubscriber_Result>("xyp_NumberAmountsByInSubscriber", startDateParameterParameter, endDateParameterParameter, usuarioParameter, llamEntradParameter, extensParameter);
        }
    
        public virtual ObjectResult<xyp_SelConsumeByExtensionAndUser_Result> xyp_SelConsumeByExtensionAndUser(string startDateParameter, string endDateParameter, string usuario, string area, string extensionParameter, string cobertura, string destino)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(string));
    
            var extensionParameterParameter = extensionParameter != null ?
                new ObjectParameter("ExtensionParameter", extensionParameter) :
                new ObjectParameter("ExtensionParameter", typeof(string));
    
            var coberturaParameter = cobertura != null ?
                new ObjectParameter("Cobertura", cobertura) :
                new ObjectParameter("Cobertura", typeof(string));
    
            var destinoParameter = destino != null ?
                new ObjectParameter("Destino", destino) :
                new ObjectParameter("Destino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelConsumeByExtensionAndUser_Result>("xyp_SelConsumeByExtensionAndUser", startDateParameterParameter, endDateParameterParameter, usuarioParameter, areaParameter, extensionParameterParameter, coberturaParameter, destinoParameter);
        }
    
        public virtual int xyp_DelRolUser(Nullable<int> id_Usuario)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_DelRolUser", id_UsuarioParameter);
        }
    
        public virtual int xyp_RolUser(Nullable<int> id_Roles, Nullable<int> id_Usuario)
        {
            var id_RolesParameter = id_Roles.HasValue ?
                new ObjectParameter("Id_Roles", id_Roles) :
                new ObjectParameter("Id_Roles", typeof(int));
    
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_RolUser", id_RolesParameter, id_UsuarioParameter);
        }
    
        public virtual int xyp_UpdRolUser(Nullable<int> id_Roles, Nullable<int> id_Usuario)
        {
            var id_RolesParameter = id_Roles.HasValue ?
                new ObjectParameter("Id_Roles", id_Roles) :
                new ObjectParameter("Id_Roles", typeof(int));
    
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("Id_Usuario", id_Usuario) :
                new ObjectParameter("Id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_UpdRolUser", id_RolesParameter, id_UsuarioParameter);
        }
    
        public virtual int xyp_UpdNumber(string ideNumber, Nullable<int> tipExtension, Nullable<int> idcliente_)
        {
            var ideNumberParameter = ideNumber != null ?
                new ObjectParameter("ideNumber", ideNumber) :
                new ObjectParameter("ideNumber", typeof(string));
    
            var tipExtensionParameter = tipExtension.HasValue ?
                new ObjectParameter("tipExtension", tipExtension) :
                new ObjectParameter("tipExtension", typeof(int));
    
            var idcliente_Parameter = idcliente_.HasValue ?
                new ObjectParameter("idcliente_", idcliente_) :
                new ObjectParameter("idcliente_", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_UpdNumber", ideNumberParameter, tipExtensionParameter, idcliente_Parameter);
        }
    
        public virtual ObjectResult<xyp_SelDialedNumber_Result> xyp_SelDialedNumber(string startDateParameter, string endDateParameter, string origen, string destino)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            var destinoParameter = destino != null ?
                new ObjectParameter("Destino", destino) :
                new ObjectParameter("Destino", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelDialedNumber_Result>("xyp_SelDialedNumber", startDateParameterParameter, endDateParameterParameter, origenParameter, destinoParameter);
        }
    
        public virtual int xyp_cambiarclave(Nullable<int> id_user, string clave)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_cambiarclave", id_userParameter, claveParameter);
        }
    
        public virtual int xyp_InsRepProg(Nullable<int> reporteId_, string nombre_, Nullable<System.DateTime> horaEjecucion_, string formatoArchivo_, string emailFrom_, string emailCC_, string asunto_, string mensaje_, string filtro_, Nullable<int> frecuenciaId_, string fechaInicial_, string fechaFinal_, string tipoFrecuencia_, Nullable<int> programacion_)
        {
            var reporteId_Parameter = reporteId_.HasValue ?
                new ObjectParameter("ReporteId_", reporteId_) :
                new ObjectParameter("ReporteId_", typeof(int));
    
            var nombre_Parameter = nombre_ != null ?
                new ObjectParameter("Nombre_", nombre_) :
                new ObjectParameter("Nombre_", typeof(string));
    
            var horaEjecucion_Parameter = horaEjecucion_.HasValue ?
                new ObjectParameter("HoraEjecucion_", horaEjecucion_) :
                new ObjectParameter("HoraEjecucion_", typeof(System.DateTime));
    
            var formatoArchivo_Parameter = formatoArchivo_ != null ?
                new ObjectParameter("FormatoArchivo_", formatoArchivo_) :
                new ObjectParameter("FormatoArchivo_", typeof(string));
    
            var emailFrom_Parameter = emailFrom_ != null ?
                new ObjectParameter("EmailFrom_", emailFrom_) :
                new ObjectParameter("EmailFrom_", typeof(string));
    
            var emailCC_Parameter = emailCC_ != null ?
                new ObjectParameter("EmailCC_", emailCC_) :
                new ObjectParameter("EmailCC_", typeof(string));
    
            var asunto_Parameter = asunto_ != null ?
                new ObjectParameter("Asunto_", asunto_) :
                new ObjectParameter("Asunto_", typeof(string));
    
            var mensaje_Parameter = mensaje_ != null ?
                new ObjectParameter("Mensaje_", mensaje_) :
                new ObjectParameter("Mensaje_", typeof(string));
    
            var filtro_Parameter = filtro_ != null ?
                new ObjectParameter("Filtro_", filtro_) :
                new ObjectParameter("Filtro_", typeof(string));
    
            var frecuenciaId_Parameter = frecuenciaId_.HasValue ?
                new ObjectParameter("FrecuenciaId_", frecuenciaId_) :
                new ObjectParameter("FrecuenciaId_", typeof(int));
    
            var fechaInicial_Parameter = fechaInicial_ != null ?
                new ObjectParameter("fechaInicial_", fechaInicial_) :
                new ObjectParameter("fechaInicial_", typeof(string));
    
            var fechaFinal_Parameter = fechaFinal_ != null ?
                new ObjectParameter("fechaFinal_", fechaFinal_) :
                new ObjectParameter("fechaFinal_", typeof(string));
    
            var tipoFrecuencia_Parameter = tipoFrecuencia_ != null ?
                new ObjectParameter("TipoFrecuencia_", tipoFrecuencia_) :
                new ObjectParameter("TipoFrecuencia_", typeof(string));
    
            var programacion_Parameter = programacion_.HasValue ?
                new ObjectParameter("Programacion_", programacion_) :
                new ObjectParameter("Programacion_", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_InsRepProg", reporteId_Parameter, nombre_Parameter, horaEjecucion_Parameter, formatoArchivo_Parameter, emailFrom_Parameter, emailCC_Parameter, asunto_Parameter, mensaje_Parameter, filtro_Parameter, frecuenciaId_Parameter, fechaInicial_Parameter, fechaFinal_Parameter, tipoFrecuencia_Parameter, programacion_Parameter);
        }
    
        public virtual ObjectResult<xyp_GrupNumSuscriber_Result> xyp_GrupNumSuscriber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_GrupNumSuscriber_Result>("xyp_GrupNumSuscriber");
        }
    
        public virtual ObjectResult<xyp_DestinoLlamadaCampeonaArea_Result> xyp_DestinoLlamadaCampeonaArea()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_DestinoLlamadaCampeonaArea_Result>("xyp_DestinoLlamadaCampeonaArea");
        }
    
        public virtual ObjectResult<xyp_RepSabanaCalls_Result> xyp_RepSabanaCalls(string startDateParameter, string endDateParameter)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_RepSabanaCalls_Result>("xyp_RepSabanaCalls", startDateParameterParameter, endDateParameterParameter);
        }
    
        public virtual int xyp_ProxEjecucionReporte(string fechaProxRepor, string idRepor)
        {
            var fechaProxReporParameter = fechaProxRepor != null ?
                new ObjectParameter("FechaProxRepor", fechaProxRepor) :
                new ObjectParameter("FechaProxRepor", typeof(string));
    
            var idReporParameter = idRepor != null ?
                new ObjectParameter("IdRepor", idRepor) :
                new ObjectParameter("IdRepor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xyp_ProxEjecucionReporte", fechaProxReporParameter, idReporParameter);
        }
    
        public virtual ObjectResult<xyp_SelUsuarios_Result> xyp_SelUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelUsuarios_Result>("xyp_SelUsuarios");
        }
    
        public virtual ObjectResult<xyp_SelAreas_Result> xyp_SelAreas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelAreas_Result>("xyp_SelAreas");
        }
    
        public virtual ObjectResult<xyp_SelDetailChampCallDuration_Result> xyp_SelDetailChampCallDuration(string startDateParameter, string endDateParameter, string area, string llamEntrad)
        {
            var startDateParameterParameter = startDateParameter != null ?
                new ObjectParameter("StartDateParameter", startDateParameter) :
                new ObjectParameter("StartDateParameter", typeof(string));
    
            var endDateParameterParameter = endDateParameter != null ?
                new ObjectParameter("EndDateParameter", endDateParameter) :
                new ObjectParameter("EndDateParameter", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(string));
    
            var llamEntradParameter = llamEntrad != null ?
                new ObjectParameter("LlamEntrad", llamEntrad) :
                new ObjectParameter("LlamEntrad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<xyp_SelDetailChampCallDuration_Result>("xyp_SelDetailChampCallDuration", startDateParameterParameter, endDateParameterParameter, areaParameter, llamEntradParameter);
        }
    }
}
